import os
import ssl
import re
from dotenv import load_dotenv
import sendgrid
from sendgrid.helpers.mail import Mail

ssl._create_default_https_context = ssl._create_unverified_context
load_dotenv()

def _to_html(body: str) -> str:
    """Convert plain-text document body to clean HTML email."""
    lines = body.splitlines()
    html_lines = []

    for line in lines:
        stripped = line.strip()

        if not stripped:
            html_lines.append('<div style="margin-bottom:12px;"></div>')
            continue

        # Section dividers (━━━ lines)
        if re.match(r'^[━\-=]{6,}$', stripped):
            html_lines.append('<hr style="border:none;border-top:1px solid #e0e0e0;margin:16px 0;">')
            continue

        # ALL-CAPS section headers (e.g. CLINICAL HISTORY:, S — SUBJECTIVE)
        if re.match(r'^[A-Z0-9 /\-—:]{4,}$', stripped) and len(stripped) < 60:
            html_lines.append(
                f'<div style="font-size:11px;font-weight:700;letter-spacing:1px;'
                f'text-transform:uppercase;color:#6b7280;margin:20px 0 6px;">{stripped}</div>'
            )
            continue

        # Field rows with colon (e.g. "Patient Name : Julie Andrews")
        if re.match(r'^[\w /\-]+\s*:', stripped) and len(stripped) < 120:
            parts = stripped.split(':', 1)
            label = parts[0].strip()
            value = parts[1].strip() if len(parts) > 1 else ''
            if value and value.lower() != 'not documented':
                html_lines.append(
                    f'<div style="margin-bottom:6px;">'
                    f'<span style="font-weight:600;color:#374151;min-width:160px;display:inline-block;">{label}:</span>'
                    f'<span style="color:#111827;">{value}</span>'
                    f'</div>'
                )
            elif not value:
                html_lines.append(
                    f'<div style="margin-bottom:6px;">'
                    f'<span style="font-weight:600;color:#374151;">{label}</span>'
                    f'</div>'
                )
            continue

        # Numbered list items
        if re.match(r'^\d+\.', stripped):
            html_lines.append(
                f'<div style="margin-bottom:8px;padding-left:20px;">{stripped}</div>'
            )
            continue

        # Regular paragraph text
        html_lines.append(
            f'<p style="margin:0 0 10px;color:#111827;line-height:1.65;">{stripped}</p>'
        )

    inner = '\n'.join(html_lines)

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="margin:0;padding:0;background:#f3f4f6;font-family:'Helvetica Neue',Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f3f4f6;padding:32px 16px;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:10px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,0.08);">

        <!-- Header -->
        <tr>
          <td style="background:linear-gradient(135deg,#0a2540,#00838f);padding:28px 36px;">
            <div style="font-family:Georgia,serif;font-size:24px;color:#ffffff;letter-spacing:-0.3px;">IntelliCare</div>
            <div style="font-size:13px;color:rgba(255,255,255,0.7);margin-top:4px;">AI-Powered Clinical Assistant</div>
          </td>
        </tr>

        <!-- Body -->
        <tr>
          <td style="padding:32px 36px;font-size:14px;color:#111827;">
            {inner}
          </td>
        </tr>

        <!-- Footer -->
        <tr>
          <td style="background:#f9fafb;padding:20px 36px;border-top:1px solid #e5e7eb;">
            <p style="margin:0;font-size:12px;color:#9ca3af;line-height:1.6;">
              This document was generated by IntelliCare and is intended for the named recipient only.
              If you received this in error, please disregard.
            </p>
          </td>
        </tr>

      </table>
    </td></tr>
  </table>
</body>
</html>"""


def send_patient_email(patient_email: str, subject: str, body: str, visit_id: str):
    sg = sendgrid.SendGridAPIClient(api_key=os.getenv("SENDGRID_API_KEY"))

    message = Mail(
        from_email=os.getenv("SENDGRID_FROM"),
        to_emails=patient_email,
        subject=subject,
        plain_text_content=body,
        html_content=_to_html(body)
    )

    response = sg.send(message)
    print(f"Email sent to {patient_email} | Status: {response.status_code} | Visit: {visit_id}")
    return response.status_code
